version: '3.8'

services:
  jira:
    image: teamatldocker/jira
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/modul347db
      - ATL_JDBC_USER=modul347
      - ATL_JDBC_PASSWORD=modul347StrongPass!
      - ATL_DB_TYPE=postgres72
      - ATL_DB_SCHEMA=public
      - ATL_JDBC_DRIVER=org.postgresql.Driver
      - ATL_DB_DRIVER=org.postgresql.Driver
    volumes:
      - jira_data:/var/atlassian/jira
    restart: always

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=modul347db
      - POSTGRES_USER=modul347
      - POSTGRES_PASSWORD=modul347StrongPass!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  jira_data:
  postgres_data:
